### ISSUE TITLE
Responder fails to create tables in MariaDB

### ISSUE THREAD

**Issue by elsif2** [En-Query/EncryptedQuery#3]
```
Caused by: java.sql.SQLSyntaxErrorException: (conn=337) Specified key was too long; max key length is 767 bytes
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236) ~[?:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165) ~[?:?]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238) ~[?:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356) ~[?:?]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:407) ~[?:?]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352) ~[?:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57) ~[?:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[?:?]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229) ~[?:?]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211) ~[?:?]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600) ~[?:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[?:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78) ~[?:?]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[?:?]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[?:?]
	at liquibase.Liquibase.update(Liquibase.java:175) ~[?:?]
	at org.enquery.encryptedquery.responder.data.maint.Migration.prepare(Migration.java:57) ~[?:?]
	at org.enquery.encryptedquery.responder.data.maint.Migration.prepare(Migration.java:45) ~[?:?]
	... 31 more
Caused by: java.sql.SQLException: Specified key was too long; max key length is 767 bytes
Query is: CREATE TABLE QRTZ_JOB_DETAILS(
SCHED_NAME VARCHAR(120) NOT NULL,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
DESCRIPTION VARCHAR(250) NULL,
JOB_CLASS_NAME VARCHAR(250) NOT NULL,
IS_DURABLE VARCHAR(1) NOT NULL,
IS_NONCONCURRENT VARCHAR(1) NOT NULL,
IS_UPDATE_DATA VARCHAR(1) NOT NULL,
REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
JOB_DATA BLOB NULL,
PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP))
ENGINE=InnoDB
```

Fix is to add ENGINE=InnoDB default charset=utf8

**Comment by wstreaker021** [comment]
Spooling up an Ubuntu system to test this.
